# Server
server.port=8082

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/event?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=false
spring.jpa.properties.hibernate.globally_quoted_identifiers_skip_column_definitions=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=EventSphereSecretKey2025SmartEventManagementSystemTanzania
app.jwt.expiration=86400000

# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sadikdickson0028@gmail.com
spring.mail.password=sdcu hldy jacm odos

spring.mail.from=sadikdickson0028@gmail.com
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.from=noreply@eventsphere.com

# Africa's Talking SMS
africastalking.api-key=atsk_b707bf5bffaf373111b39bcf5bd25a5172b297cde82a21635ff5e20c9a027cba0780d07f
africastalking.username=eventsphere
africastalking.sender-id=
//atsk_b707bf5bffaf373111b39bcf5bd25a5172b297cde82a21635ff5e20c9a027cba0780d07f
# File Upload
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=./uploads
app.cards.dir=./generated-cards
# Multipart upload config
spring.servlet.multipart.resolve-lazily=false

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
#app.cors.allowed-origins=http://localhost:5173
# Logging
logging.level.com.eventsphere=INFO
#logging.level.org.springframework.security=WARN
#logging.level.org.springframework.security=TRACE
#logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.example.eventsphere=DEBUG
