<template>
  <div>
    <button class="btn btn-g btn-sm mb2" @click="$router.push('/organizer/events')">
      <i class="fas fa-arrow-left"></i> Back to My Events
    </button>
    <div v-if="loading" class="loading-box"><i class="fas fa-spinner fa-spin"></i> Loading...</div>
    <div v-else-if="event">
      <div class="event-header">
        <div>
          <h2>{{ event.eventName }}</h2>
          <div class="meta">
            <span><i class="fas fa-calendar"></i> {{ event.eventDate }}</span>
            <span><i class="fas fa-map-marker-alt"></i> {{ event.venue }}</span>
            <span><i class="fas fa-users"></i> {{ event.capacity }} capacity</span>
          </div>
        </div>
        <div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap">
          <StatusBadge :status="event.status" />
          <button v-if="event.status === 'APPROVED' && event.payment?.status === 'APPROVED'"
            class="btn btn-p btn-sm" @click="$router.push(`/organizer/invitations/${event.id}`)">
            <i class="fas fa-envelope"></i> Manage Invitations
          </button>
        </div>
      </div>

      <div class="gr2 mt2">
        <div class="card">
          <div class="ct mb2">Event Details</div>
          <div class="info-grid">
            <div><span class="lbl">Category</span>{{ event.category?.replace('_',' ') }}</div>
            <div><span class="lbl">Layout</span>{{ event.selectedLayout }}</div>
            <div><span class="lbl">Start</span>{{ event.startTime }}</div>
            <div><span class="lbl">End</span>{{ event.endTime }}</div>
            <div><span class="lbl">Contact</span>{{ event.contactInfo }}</div>
            <div><span class="lbl">Amount</span><strong style="color:var(--p)">${{ event.totalAmount }}</strong></div>
          </div>
          <div v-if="event.description" class="desc-box mt2">
            <div class="lbl mb1">Description (on invitation cards)</div>
            {{ event.description }}
          </div>
          <div v-if="event.adminRemarks" class="al al-in mt2">
            <i class="fas fa-info-circle"></i>
            <div><strong>Admin Remarks:</strong> {{ event.adminRemarks }}</div>
          </div>
        </div>
        <div class="card">
          <div class="ct mb2">Payment</div>
          <div v-if="event.payment">
            <div class="pay-row"><span>Invoice</span><code>{{ event.payment.invoiceNumber }}</code></div>
            <div class="pay-row"><span>Amount</span><strong>${{ event.payment.amount }}</strong></div>
            <div class="pay-row"><span>Status</span><StatusBadge :status="event.payment.status" /></div>
            <div class="pay-row">
              <span>Proof</span>
              <span v-if="event.payment.hasProof" class="badge badge-ok"><i class="fas fa-paperclip"></i> Uploaded</span>
              <span v-else class="badge badge-wa">Not uploaded</span>
            </div>
            <button v-if="event.payment.status === 'PENDING' || event.payment.status === 'REJECTED'"
              class="btn btn-wa btn-full mt2" @click="showUpload = true">
              <i class="fas fa-upload"></i> Upload Payment Proof
            </button>
            <div v-if="event.payment.status === 'UNDER_REVIEW'" class="al al-in mt2">
              <i class="fas fa-clock"></i> Payment proof under review. You'll be notified when verified.
            </div>
          </div>

          <div class="ct mt2 mb2">Invitation Cards</div>
          <div v-if="event.generatedCards > 0" class="cards-info">
            <div class="badge badge-ok" style="font-size:14px;padding:8px 14px">
              <i class="fas fa-envelope"></i> {{ event.generatedCards }} cards generated
            </div>
            <button class="btn btn-p btn-full mt2" @click="$router.push(`/organizer/invitations/${event.id}`)">
              <i class="fas fa-paper-plane"></i> Send to Participants
            </button>
          </div>
          <div v-else class="al al-wa">
            <i class="fas fa-hourglass-half"></i>
            Cards will be generated by admin after payment approval.
          </div>
        </div>
      </div>
    </div>

    <!-- Upload Modal -->
    <AppModal v-model="showUpload" title="Upload Payment Proof">
      <div class="upz" @click="$refs.fileIn.click()">
        <i class="fas fa-cloud-upload-alt" style="font-size:36px;color:var(--tx3);margin-bottom:10px;display:block"></i>
        <div class="fw6 mb1">Click or drop payment receipt</div>
        <div class="tx3c txs">JPG, PNG, PDF – max 10MB</div>
        <div v-if="proofFile" class="badge badge-ok mt2">{{ proofFile.name }}</div>
        <input ref="fileIn" type="file" style="display:none" accept=".jpg,.jpeg,.png,.pdf" @change="e => proofFile = e.target.files[0]" />
      </div>
      <template #footer>
        <button class="btn btn-g" @click="showUpload = false">Cancel</button>
        <button class="btn btn-p" @click="doUpload" :disabled="!proofFile || uploading">
          <i v-if="uploading" class="fas fa-spinner fa-spin"></i>
          <i v-else class="fas fa-upload"></i> Upload
        </button>
      </template>
    </AppModal>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { orgApi } from '../../api'
import { useToast } from 'vue-toastification'
import StatusBadge from '../../components/StatusBadge.vue'
import AppModal from '../../components/AppModal.vue'

const route = useRoute()
const toast = useToast()
const event = ref(null)
const loading = ref(true)
const showUpload = ref(false)
const proofFile = ref(null)
const uploading = ref(false)

async function load() {
  loading.value = true
  try {
    const { data } = await orgApi.getEvent(route.params.id)
    event.value = data.data
  } catch (e) {
    toast.error('Failed to load event')
  } finally {
    loading.value = false
  }
}

async function doUpload() {
  if (!proofFile.value || !event.value?.payment?.id) return
  uploading.value = true
  try {
    await orgApi.uploadProof(event.value.payment.id, proofFile.value)
    event.value.payment.status = 'UNDER_REVIEW'
    event.value.payment.hasProof = true
    showUpload.value = false
    toast.success('Proof uploaded! Admin will review and notify you via email & SMS.')
  } catch (e) {
    toast.error('Upload failed')
  } finally {
    uploading.value = false
  }
}

onMounted(load)
</script>

<style scoped>
.loading-box { padding: 60px; text-align: center; color: var(--tx3); }
.event-header { display: flex; align-items: flex-start; justify-content: space-between; flex-wrap: wrap; gap: 14px; }
.event-header h2 { font-size: 22px; font-weight: 800; margin-bottom: 6px; }
.meta { display: flex; gap: 14px; flex-wrap: wrap; font-size: 13px; color: var(--tx2); }
.meta span { display: flex; align-items: center; gap: 5px; }
.gr2 { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; }
.ct { font-size: 15px; font-weight: 600; }
.lbl { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: .4px; color: var(--tx3); display: block; margin-bottom: 2px; }
.info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; font-size: 13px; }
.desc-box { background: var(--bg3); border-radius: 8px; padding: 14px; font-size: 13px; color: var(--tx2); }
.pay-row { display: flex; justify-content: space-between; align-items: center; padding: 8px 0; border-bottom: 1px solid var(--bd); font-size: 13px; }
.pay-row:last-child { border-bottom: none; }
.fw6 { font-weight: 600; }
@media (max-width: 900px) { .gr2 { grid-template-columns: 1fr; } }
</style>
